# Generated by Django 4.1.6 on 2023-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='نام')),
                ('lname', models.CharField(max_length=8, verbose_name='نام خانوادگی')),
                ('img', models.ImageField(upload_to='', verbose_name='عکس')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('date', models.DateField(verbose_name='عکس')),
            ],
        ),
    ]
